# Generated by Django 3.0.3 on 2020-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
